[general]
live_config_reload = true
import = [
  "~/.config/alacritty/themes/catppuccin_frappe.toml"
]

[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 20
y = 20

[font]
size = 18.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]

